version: '3.8'

services:
  # Tools Service Database
  mysql-tools:
    image: mysql:8.0
    container_name: mysql-tools
    environment:
      MYSQL_ROOT_PASSWORD: Isi6426192,
      MYSQL_DATABASE: tool_db
    ports:
      - "3307:3306"
    restart: unless-stopped

  # Loans Service Database
  mysql-loans:
    image: mysql:8.0
    container_name: mysql-loans
    environment:
      MYSQL_ROOT_PASSWORD: Isi6426192,
      MYSQL_DATABASE: loan_db
    ports:
      - "3308:3306"
    restart: unless-stopped

  # Customers Service Database
  mysql-customers:
    image: mysql:8.0
    container_name: mysql-customers
    environment:
      MYSQL_ROOT_PASSWORD: Isi6426192,
      MYSQL_DATABASE: customer_db
    ports:
      - "3309:3306"
    restart: unless-stopped

  # Tariffs Service Database
  mysql-tariffs:
    image: mysql:8.0
    container_name: mysql-tariffs
    environment:
      MYSQL_ROOT_PASSWORD: Isi6426192,
      MYSQL_DATABASE: tariff_db
    ports:
      - "3310:3306"
    restart: unless-stopped

  # Kardex Service Database
  mysql-kardex:
    image: mysql:8.0
    container_name: mysql-kardex
    environment:
      MYSQL_ROOT_PASSWORD: Isi6426192,
      MYSQL_DATABASE: kardex_db
    ports:
      - "3311:3306"
    restart: unless-stopped

  # Reports Service Database
  mysql-reports:
    image: mysql:8.0
    container_name: mysql-reports
    environment:
      MYSQL_ROOT_PASSWORD: Isi6426192,
      MYSQL_DATABASE: report_db
    ports:
      - "3312:3306"
    restart: unless-stopped

  # Users Service Database
  mysql-users:
    image: mysql:8.0
    container_name: mysql-users
    environment:
      MYSQL_ROOT_PASSWORD: Isi6426192,
      MYSQL_DATABASE: user_db
    ports:
      - "3313:3306"
    restart: unless-stopped