spring:
  application:
    name: users-service
  config:
    import: optional:configserver:http://localhost:8081
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/toolrent-realm